### PR TITLE
Add cancel event

### PR DESCRIPTION
**Pull request by AdaRoseCannon**
In my use case, using hand tracking to fire the blink events sometimes the user points for a few frames but not long enough to trigger the blink so in that situation I want to cancel it so that the line and hit entity disappear.

This allows it to listen for a cancel event which stops the blink.

### CODE REVIEW

**Comment by jure** [comment]
This looks very useful and I like the implementation! 

Any chance you could add an example of how it can be used too?

**Comment by AdaRoseCannon** [comment]
Sure, where do you want the example?

**Comment by jure** [comment]
The examples live on this GitHub Pages site (https://jure.github.io/aframe-blink-controls/), and the source for them is in this repo's `docs` folder (https://github.com/jure/aframe-blink-controls/tree/main/docs). In order to not increase the number of examples for this, I think the terrain example would be a good place to demonstrate the cancel functionality, since the title of it is 'Example with curved terrain and events'.

What do you think?

**Comment by AdaRoseCannon** [comment]
Sure.

**Comment by AdaRoseCannon** [comment]
If it detects a squeeze or gripdown event it cancels the navigation

**Comment by jure** [comment]
Thank you so much, Ada! Apologies for the late response - to try and make it right I've now also released a new version of aframe-blink-controls.

**Pull request merged**
